Option Explicit

Dim fso, tempFolder, htaFile, htaPath, shell, exec
Set fso = CreateObject("Scripting.FileSystemObject")
Set shell = CreateObject("WScript.Shell")

' create the temporary folder
tempFolder = fso.GetAbsolutePathName(".") & "\temp"
If Not fso.FolderExists(tempFolder) Then fso.CreateFolder tempFolder

htaPath = tempFolder & "\MVTXT.HTA"

' create the application
Set htaFile = fso.CreateTextFile(htaPath, True)

htaFile.WriteLine "<html>"
htaFile.WriteLine "<head>"
htaFile.WriteLine "  <title>MVTXT</title>"
htaFile.WriteLine "  <HTA:APPLICATION "
htaFile.WriteLine "    ID=""MVTXTApp"""
htaFile.WriteLine "    APPLICATIONNAME=""MVTXT Text Editor"""
htaFile.WriteLine "    BORDER=""thin"""
htaFile.WriteLine "    BORDERSTYLE=""normal"""
htaFile.WriteLine "    CAPTION=""yes"""
htaFile.WriteLine "    SHOWINTASKBAR=""yes"""
htaFile.WriteLine "    SINGLEINSTANCE=""yes"""
htaFile.WriteLine "    SYSMENU=""yes"""
htaFile.WriteLine "    SCROLL=""no"""
htaFile.WriteLine "  />"
htaFile.WriteLine "  <script language=""VBScript"">"
htaFile.WriteLine "    Dim configPath"
htaFile.WriteLine "    configPath = GetAppPath() & ""\mvtxt_config.txt"""
htaFile.WriteLine ""
htaFile.WriteLine "    Sub Window_OnLoad()"
htaFile.WriteLine "      ResizeEditor"
htaFile.WriteLine "      LoadOrCreateConfig"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub LoadOrCreateConfig()"
htaFile.WriteLine "      Dim fso, file, font, size"
htaFile.WriteLine "      Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "      If fso.FileExists(configPath) Then"
htaFile.WriteLine "        Set file = fso.OpenTextFile(configPath, 1)"
htaFile.WriteLine "        font = file.ReadLine"
htaFile.WriteLine "        size = file.ReadLine"
htaFile.WriteLine "        file.Close"
htaFile.WriteLine "      Else"
htaFile.WriteLine "        font = ""Consolas"""
htaFile.WriteLine "        size = ""14"""
htaFile.WriteLine "        Set file = fso.CreateTextFile(configPath, True)"
htaFile.WriteLine "        file.WriteLine font"
htaFile.WriteLine "        file.WriteLine size"
htaFile.WriteLine "        file.Close"
htaFile.WriteLine "      End If"
htaFile.WriteLine "      If font <> """" Then editor.style.fontFamily = font"
htaFile.WriteLine "      If size <> """" Then editor.style.fontSize = size & ""pt"""
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Function GetAppPath()"
htaFile.WriteLine "      Dim fso, fullPath"
htaFile.WriteLine "      Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "      fullPath = fso.GetAbsolutePathName(""."")"
htaFile.WriteLine "      GetAppPath = fullPath"
htaFile.WriteLine "    End Function"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub SaveText()"
htaFile.WriteLine "      Dim fso, file, path"
htaFile.WriteLine "      path = InputBox(""Enter full path to save (e.g. C:\Users\You\Desktop\file.txt):"", ""Save File As"")"
htaFile.WriteLine "      If path <> """" Then"
htaFile.WriteLine "        Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "        On Error Resume Next"
htaFile.WriteLine "        Set file = fso.CreateTextFile(path, True)"
htaFile.WriteLine "        If Err.Number <> 0 Then"
htaFile.WriteLine "          MsgBox ""Error saving file: "" & Err.Description, vbCritical, ""Error!"""
htaFile.WriteLine "          Exit Sub"
htaFile.WriteLine "        End If"
htaFile.WriteLine "        file.WriteLine document.getElementById(""editor"").value"
htaFile.WriteLine "        file.Close"
htaFile.WriteLine "        MsgBox ""File saved to: "" & path"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub LoadText()"
htaFile.WriteLine "      Dim fso, file, path, content"
htaFile.WriteLine "      path = InputBox(""Enter full path of file to load:"", ""Open File"")"
htaFile.WriteLine "      If path <> """" Then"
htaFile.WriteLine "        Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "        If Not fso.FileExists(path) Then"
htaFile.WriteLine "          MsgBox ""File not found."", vbExclamation, ""Error!"""
htaFile.WriteLine "          Exit Sub"
htaFile.WriteLine "        End If"
htaFile.WriteLine "        On Error Resume Next"
htaFile.WriteLine "        Set file = fso.OpenTextFile(path, 1)"
htaFile.WriteLine "        If Err.Number <> 0 Then"
htaFile.WriteLine "          MsgBox ""Error loading file: "" & Err.Description, vbCritical, ""Error!"""
htaFile.WriteLine "          Exit Sub"
htaFile.WriteLine "        End If"
htaFile.WriteLine "        content = file.ReadAll"
htaFile.WriteLine "        file.Close"
htaFile.WriteLine "        document.getElementById(""editor"").value = content"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub ChangeFont()"
htaFile.WriteLine "      Dim font, size, fso, file"
htaFile.WriteLine "      font = InputBox(""Enter font name (e.g., Arial, Courier New):"", ""Font"")"
htaFile.WriteLine "      size = InputBox(""Enter font size (1 - 100):"", ""Font Size"")"
htaFile.WriteLine "      If font <> """" And size <> """" Then"
htaFile.WriteLine "        If IsNumeric(size) And CInt(size) > 1 And CInt(size) <= 100 Then"
htaFile.WriteLine "          editor.style.fontFamily = font"
htaFile.WriteLine "          editor.style.fontSize = size & ""pt"""
htaFile.WriteLine "          Set fso = CreateObject(""Scripting.FileSystemObject"")"
htaFile.WriteLine "          Set file = fso.CreateTextFile(configPath, True)"
htaFile.WriteLine "          file.WriteLine font"
htaFile.WriteLine "          file.WriteLine size"
htaFile.WriteLine "          file.Close"
htaFile.WriteLine "        Else"
htaFile.WriteLine "          MsgBox ""Please enter a valid font size (1 - 100)."", vbExclamation, ""Invalid Font Size!"""
htaFile.WriteLine "        End If"
htaFile.WriteLine "      End If"
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub ShowAbout()"
htaFile.WriteLine "      MsgBox ""MVTXT - A basic text editor made by mayci_voxel!"" & vbCrLf & ""HTA-based. Made with <3"", vbInformation, ""About MVTXT"""
htaFile.WriteLine "    End Sub"
htaFile.WriteLine ""
htaFile.WriteLine "    Sub ResizeEditor()"
htaFile.WriteLine "      Dim height"
htaFile.WriteLine "      height = document.body.clientHeight - document.getElementById(""toolbar"").offsetHeight"
htaFile.WriteLine "      document.getElementById(""editor"").style.height = height & ""px"""
htaFile.WriteLine "    End Sub"
htaFile.WriteLine "  </script>"
htaFile.WriteLine ""
htaFile.WriteLine "  <style>"
htaFile.WriteLine "    html, body { margin: 0; padding: 0; overflow: hidden; height: 100%; }"
htaFile.WriteLine "    #toolbar { background: #222; color: white; padding: 10px; font-family: Segoe UI, sans-serif; }"
htaFile.WriteLine "    button { margin-right: 10px; font-size: 14px; cursor: pointer; }"
htaFile.WriteLine "    #editor { width: 100%; font-family: Consolas, monospace; font-size: 14pt; padding: 10px; box-sizing: border-box; border: none; resize: none; }"
htaFile.WriteLine "  </style>"
htaFile.WriteLine "</head>"
htaFile.WriteLine "<body onresize=""ResizeEditor"">"
htaFile.WriteLine "  <div id=""toolbar"">"
htaFile.WriteLine "    <button onclick=""SaveText()"">Save</button>"
htaFile.WriteLine "    <button onclick=""LoadText()"">Load</button>"
htaFile.WriteLine "    <button onclick=""ChangeFont()"">Font</button>"
htaFile.WriteLine "    <button onclick=""ShowAbout()"">About</button>"
htaFile.WriteLine "  </div>"
htaFile.WriteLine "  <textarea id=""editor""></textarea>"
htaFile.WriteLine "</body>"
htaFile.WriteLine "</html>"

htaFile.Close

' hide it,,
shell.Run "attrib +h """ & htaPath & """", 0, True

' launch it and begin waiting
Set exec = shell.Exec("mshta.exe """ & htaPath & """")

Do While exec.Status = 0
    WScript.Sleep 500
Loop

' clean up
On Error Resume Next
fso.DeleteFile htaPath, True
On Error GoTo 0
